/* SPDX-License-Identifier: GPL-2.0+ WITH Linux-syscall-note */
#ifndef _UAPI_MPTCP_H
#define _UAPI_MPTCP_H

#include <linux/types.h>

#define MPTCP_SUBFLOW_FLAG_MCAP_REM	BIT(0)
#define MPTCP_SUBFLOW_FLAG_MCAP_LOC	BIT(1)
#define MPTCP_SUBFLOW_FLAG_JOIN_REM	BIT(2)
#define MPTCP_SUBFLOW_FLAG_JOIN_LOC	BIT(3)
#define MPTCP_SUBFLOW_FLAG_BKUP_REM	BIT(4)
#define MPTCP_SUBFLOW_FLAG_BKUP_LOC	BIT(5)
#define MPTCP_SUBFLOW_FLAG_4THACK	BIT(6)
#define MPTCP_SUBFLOW_FLAG_CONNECTED	BIT(7)
#define MPTCP_SUBFLOW_FLAG_MAPVALID	BIT(8)

enum {
	MPTCP_SUBFLOW_ATTR_UNSPEC,
	MPTCP_SUBFLOW_ATTR_TOKEN_REM,
	MPTCP_SUBFLOW_ATTR_TOKEN_LOC,
	MPTCP_SUBFLOW_ATTR_RELWRITE_SEQ,
	MPTCP_SUBFLOW_ATTR_MAP_SEQ,
	MPTCP_SUBFLOW_ATTR_MAP_SFSEQ,
	MPTCP_SUBFLOW_ATTR_SSN_OFFSET,
	MPTCP_SUBFLOW_ATTR_MAP_DATALEN,
	MPTCP_SUBFLOW_ATTR_FLAGS,
	MPTCP_SUBFLOW_ATTR_ID_REM,
	MPTCP_SUBFLOW_ATTR_ID_LOC,
	MPTCP_SUBFLOW_ATTR_PAD,
	__MPTCP_SUBFLOW_ATTR_MAX
};

#define MPTCP_SUBFLOW_ATTR_MAX (__MPTCP_SUBFLOW_ATTR_MAX - 1)
#endif /* _UAPI_MPTCP_H */
